### ISSUE TITLE
Feature Request: Support #pickhardtpayments

### ISSUE THREAD

**Issue by C-Otto** [C-Otto/lnd-manageJ#6]
Support #pickhardtpayments as described in https://github.com/renepickhardt/mpp-splitter/blob/master/Minimal%20Linearized%20min%20cost%20flow%20example%20for%20MPP.ipynb.

- [x] compute MPP based on flow information
- [x] combine probability and fees in cost function
- [x] optimize N (number of piecewise linear approximations)
- [x] what if capacity % N != 0?
- [x] use different values for N depending on channel size?
- [x] what if amount % quantization != 0?
- [x] what if amount < quantization?
- [x] limit graph to zero base fee channels
- [x] ~~add support for non-zero base fee channels~~  (moved to #31)
- [x] consider max_htlc for channels
- [x] make use of mission control information (see #7)
- [x] send out MPP
- [x] add payment loop (deal with failed parts of MPP, try those again) (blocked by https://github.com/lightningnetwork/lnd/issues/5746)
- [x] make N, quantization, ... configurable (see #5)
- [x] ~~add switch to ignore fees of local channels (for outgoing payments)~~ (moved to #33)
- [x] solve startup issues wrt. OR tools native library loader
- [x] solve pitest issues wrt. OR tools native library loader
- [x] what if there are several parallel channels and the flow picks an amount that is more than each individual channel's capacity?
- [x] combine parallel channels?
- [x] add known liquidity for local channels
- [x] do not forget about disabled/broken channels straight away (set upper bound to 1 instead of 0?)
- [x] fail everything on first INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS failure
- [x] document middleware requirement
- [x] fix "upper bound" vs. "in flight"
- [x] handle failures:
  - [x] INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS = 1;
  - [x]         INCORRECT_PAYMENT_AMOUNT = 2;
  - [x]         FINAL_INCORRECT_CLTV_EXPIRY = 3;
  - [x]         FINAL_INCORRECT_HTLC_AMOUNT = 4;
  - [x]         FINAL_EXPIRY_TOO_SOON = 5;
  - [x]         INVALID_REALM = 6;
  - [x]         EXPIRY_TOO_SOON = 7;
  - [x]         INVALID_ONION_VERSION = 8;
  - [x]         INVALID_ONION_HMAC = 9;
  - [x]         INVALID_ONION_KEY = 10;
  - [x]         AMOUNT_BELOW_MINIMUM = 11;
  - [x]         FEE_INSUFFICIENT = 12;
  - [x]         INCORRECT_CLTV_EXPIRY = 13;
  - [x]         CHANNEL_DISABLED = 14;
  - [x]         TEMPORARY_CHANNEL_FAILURE = 15;
  - [x]         REQUIRED_NODE_FEATURE_MISSING = 16;
  - [x]         REQUIRED_CHANNEL_FEATURE_MISSING = 17;
  - [x]         UNKNOWN_NEXT_PEER = 18;
  - [x]         TEMPORARY_NODE_FAILURE = 19;
  - [x]         PERMANENT_NODE_FAILURE = 20;
  - [x]         PERMANENT_CHANNEL_FAILURE = 21;
  - [x]         EXPIRY_TOO_FAR = 22;
  - [x]         MPP_TIMEOUT = 23;
  - [x]         INVALID_ONION_PAYLOAD = 24;
  - [x]   other/unknown
